name: 'Trigger external workflow'
description: 'An action that lets you trigger workflows in another repository'
author: 'Henry Whitaker'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'scissors'
  color: 'blue'

# Define your inputs here.
inputs:
  event:
    description: 'The name of the event in the other repository'
    required: true
    default: ''
  body:
    description: 'The JSON body to send the the external workflow'
    required: false
  repo:
    description: 'The repository where you want to trigger the action'
    required: true
  token:
    description: 'The Github token to authenticate with the other repository'
    required: true
  github_api:
    description: 'The url of the Github API to run against'
    required: false
    default: 'https://api.github.com'
  

# Define your outputs here.
# outputs:
#   time:
#     description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
